apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-data-pvc
  labels: 
    name: app-data
spec:
  # storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300M