apiVersion: v1
kind: Pod
metadata:
  name: nginx-app
spec:
  volumes:
  - name: app-data-pvc
    hostPath:
      path: "/data/app-data"
  containers:
  - name: nginx-app
    image: nginx
    volumeMounts:
    - name: app-data
      mountPath: /usr/share/nginx/html